import {
  DEFAULT_STYLE,
  type RenderOptions,
  type SubtitleCue,
  type SubtitleStyle,
} from './types.js'
import { wrapCueText } from './wrap.js'

/**
 * 生成 SSA / ASS V4+ 格式字幕文件。
 *
 * 协议参考：
 *   - http://www.tcax.org/docs/ass-specs.htm
 *   - libass 支持的语法（与 VSFilter 大致兼容）
 *
 * 输出可被 ffmpeg `subtitles=` filter 直接烧入视频。
 */
export function renderAss(cues: SubtitleCue[], opts: RenderOptions): string {
  const style: SubtitleStyle = { ...DEFAULT_STYLE, ...opts.style }
  const { metrics } = opts
  // 字号按 1080p 基准等比缩放，避免在不同分辨率上看起来不一致
  const scale = metrics.height / 1080
  const primarySize = Math.max(20, Math.round(style.fontSize * scale))
  const secondarySize = Math.max(16, Math.round(primarySize * style.secondaryFontScale))
  // ASS MarginV 是从底部往上的像素数；这里用 bottomMarginRatio 算
  const marginV = Math.max(20, Math.round(metrics.height * style.bottomMarginRatio))

  const primaryColor = hexToAssColor(style.primaryColor)
  const secondaryColor = hexToAssColor(style.secondaryColor)
  const outlineColor = hexToAssColor(style.outlineColor)
  const bold = style.bold ? -1 : 0

  // Header
  const lines: string[] = []
  lines.push('[Script Info]')
  lines.push('; Generated by DramaPrime v0.4')
  lines.push('ScriptType: v4.00+')
  lines.push(`PlayResX: ${metrics.width}`)
  lines.push(`PlayResY: ${metrics.height}`)
  lines.push('ScaledBorderAndShadow: yes')
  lines.push('YCbCr Matrix: TV.709')
  lines.push('WrapStyle: 0')
  lines.push('')

  // Styles 段：Primary（译文 / 唯一行）+ Secondary（原文，双语模式下用）
  lines.push('[V4+ Styles]')
  lines.push(
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
  )
  // Alignment 2 = bottom-center；BorderStyle 1 = outline + shadow
  lines.push(
    `Style: Primary,${style.primaryFont},${primarySize},${primaryColor},&H00FFFFFF,${outlineColor},&H66000000,${bold},0,0,0,100,100,0,0,1,${style.outlineWidth},${style.shadowDistance},2,40,40,${marginV},1`,
  )
  lines.push(
    `Style: Secondary,${style.secondaryFont ?? style.primaryFont},${secondarySize},${secondaryColor},&H00FFFFFF,${outlineColor},&H66000000,${bold},0,0,0,100,100,0,0,1,${style.outlineWidth},${style.shadowDistance},2,40,40,${marginV},1`,
  )
  lines.push('')

  // Events
  lines.push('[Events]')
  lines.push('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text')

  for (const cue of cues) {
    const start = msToAssTime(cue.startMs)
    const end = msToAssTime(cue.endMs)
    // 渲染前先按软上限折行（中文 18 字 / 英文 28 字默认）——避免单行"一坨"
    // 英文场景：副字幕（中文原文）和译文（英文）字符密度不同，分别用同一上限
    // 也基本 OK；未来可加 secondaryMaxCharsPerLine 区分
    const primarySrc = wrapCueText(cue.primaryText, style.maxCharsPerLine)
    const secondarySrc = cue.secondaryText
      ? wrapCueText(cue.secondaryText, style.maxCharsPerLine)
      : ''
    const primary = sanitizeAssText(primarySrc)
    const secondary = secondarySrc ? sanitizeAssText(secondarySrc) : ''

    if (opts.bilingual && secondary) {
      // 双语：中文（secondary）在上 + 译文（primary）在下，**同一条 Dialogue + \N 换行**
      // 用 Primary 样式，中间嵌入 inline override 切换字号 / 颜色到 secondary
      // \r 重置到 Style；\rSecondary 切换到 Secondary 样式
      const text = `{\\rSecondary}${secondary}\\N{\\rPrimary}${primary}`
      lines.push(`Dialogue: 0,${start},${end},Primary,,0,0,0,,${text}`)
    } else {
      lines.push(`Dialogue: 0,${start},${end},Primary,,0,0,0,,${primary}`)
    }
  }

  return lines.join('\n') + '\n'
}

/**
 * 把 ms 转 ASS 时间戳 "H:MM:SS.cc"（百分秒，2 位数）。
 */
export function msToAssTime(ms: number): string {
  if (ms < 0) ms = 0
  const totalCs = Math.round(ms / 10) // ms → 百分秒
  const cs = totalCs % 100
  const totalSec = Math.floor(totalCs / 100)
  const s = totalSec % 60
  const totalMin = Math.floor(totalSec / 60)
  const min = totalMin % 60
  const h = Math.floor(totalMin / 60)
  return `${h}:${pad2(min)}:${pad2(s)}.${pad2(cs)}`
}

/**
 * 16 进制 #RRGGBB → ASS 颜色 &H00BBGGRR（注意 BGR 顺序 + 透明度前缀 00）
 * Alpha 00 = 不透明
 */
export function hexToAssColor(hex: string): string {
  let h = hex.trim()
  if (h.startsWith('#')) h = h.slice(1)
  if (h.length === 3) {
    h = h
      .split('')
      .map((c) => c + c)
      .join('')
  }
  if (h.length !== 6) return '&H00FFFFFF' // fallback white
  const r = h.slice(0, 2).toUpperCase()
  const g = h.slice(2, 4).toUpperCase()
  const b = h.slice(4, 6).toUpperCase()
  return `&H00${b}${g}${r}`
}

/**
 * 文本里 \n 替成 \N；剥掉对 ASS 有副作用的字符。
 * libass 把 `{...}` 当作 inline override 块，所以要转义；同时保留中英文标点。
 */
export function sanitizeAssText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\r?\n/g, '\\N')
    .trim()
}

const pad2 = (n: number): string => (n < 10 ? '0' + n : String(n))
